// Copy this file to config.js and fill in your Supabase values
// For production on GitHub Pages, config.js is generated by GitHub Actions

window.SUPABASE_URL = "https://YOUR-PROJECT.supabase.co";
window.SUPABASE_ANON_KEY = "YOUR-ANON-KEY";
